apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-app

  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
      - name: jornada-product
        image: thiagoluna/product_jornada
        imagePullPolicy: Always
#        command: ["/bin/sh", "-c", "ln -s /var/www /usr/share/nginx;  php-fpm;"]
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: product-app-conf
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: product-mysql-pass
              key: password
        volumeMounts:
        - name: product-app-conf
          subPath: .env
          mountPath: /var/www/.env  
      
      volumes:
      - name: product-app-conf
        configMap:
          name: product-app-conf
          items:
            - key: env
              path: .env
