apiVersion: v1
kind: ConfigMap
metadata:
  name: product-app-conf
  labels:
    name: product-app-conf
data:
  env: |
    APP_NAME=Product
    APP_ENV=local
    APP_KEY=base64:EO82t0YoNwpYg1yvX2KrETWpyiCFZwX9MzYkMaWicA4=
    APP_DEBUG=true
    APP_URL=http://localhost

    LOG_CHANNEL=stack

    DB_CONNECTION=mysql
    DB_HOST=product-mysql-service
    DB_PORT=3306
    DB_DATABASE=productapp
    DB_USERNAME=root

    BROADCAST_DRIVER=log
    CACHE_DRIVER=file
    QUEUE_CONNECTION=sync
    SESSION_DRIVER=file
    SESSION_LIFETIME=120

    REDIS_HOST=product-redis-service
    REDIS_PASSWORD=null
    REDIS_PORT=6379

    MAIL_DRIVER=smtp
    MAIL_HOST=smtp.mailtrap.io
    MAIL_PORT=2525
    MAIL_USERNAME=null
    MAIL_PASSWORD=null
    MAIL_ENCRYPTION=null

    AWS_ACCESS_KEY_ID=
    AWS_SECRET_ACCESS_KEY=
    AWS_DEFAULT_REGION=us-east-1
    AWS_BUCKET=

    PUSHER_APP_ID=
    PUSHER_APP_KEY=
    PUSHER_APP_SECRET=
    PUSHER_APP_CLUSTER=mt1

    MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
    MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

    SAML2_PRODUCT_IDP_ENTITYID=https://app.onelogin.com/saml/metadata/e694ff8b-acc5-4f6b-b1f0-a25aa3f322ff
    SAML2_PRODUCT_IDP_SSO_URL=https://code-education.onelogin.com/trust/saml2/http-post/sso/e694ff8b-acc5-4f6b-b1f0-a25aa3f322ff
    SAML2_PRODUCT_IDP_SL_URL=https://code-education.onelogin.com/trust/saml2/http-redirect/slo/1011403
    SAML2_PRODUCT_IDP_x509="MIID8jCCAtqgAwIBAgIUNxp5rR63v7GCQnAhXaemqDMJX38wDQYJKoZIhvcNAQEFBQAwTDEXMBUGA1UECgwOY29kZS5lZHVjYXRpb24xFTATBgNVBAsMDE9uZUxvZ2luIElkUDEaMBgGA1UEAwwRT25lTG9naW4gQWNjb3VudCAwHhcNMTkxMDI5MTQxODQ1WhcNMjQxMDI5MTQxODQ1WjBMMRcwFQYDVQQKDA5jb2RlLmVkdWNhdGlvbjEVMBMGA1UECwwMT25lTG9naW4gSWRQMRowGAYDVQQDDBFPbmVMb2dpbiBBY2NvdW50IDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAM/3KU8bsIRPjDEwLOk1RWDTRC+aAMypQlYbp5LAnAWtf6DZmHrE4A/N6bkoDQbCwW6xRhu1DushW3YAqFUnKHxLMfkIay1w+hxfTpfK2qY7ki0vR5civxIml1IS6Xv7/r9MNYxrYeutsvjyodm1eEFKpw8w4LJ4JZre23QWkoU/A5a/jshwGNZQ9oP0OJFYkfqhNLoacwRQbIE182bPbXAX6xC7hhSQggV5l5lgKlSZWQKkXuNVsY9u8tNuzkPnNRk3owcXSjdeJ97bBrluGyx2mAgDD1y92kWX4/6InMywDWRYv9Yu2awv0m2RO3JiIAMnELnNoz71p6dYbigIIF0CAwEAAaOByzCByDAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQ3RTcxYZhHS31c9gjAWKOa2z1BVzCBiAYDVR0jBIGAMH6AFDdFNzFhmEdLfVz2CMBYo5rbPUFXoVCkTjBMMRcwFQYDVQQKDA5jb2RlLmVkdWNhdGlvbjEVMBMGA1UECwwMT25lTG9naW4gSWRQMRowGAYDVQQDDBFPbmVMb2dpbiBBY2NvdW50IIIUNxp5rR63v7GCQnAhXaemqDMJX38wDgYDVR0PAQH/BAQDAgeAMA0GCSqGSIb3DQEBBQUAA4IBAQCfNXDO00b8386ZWASv7zIxanWfF1YH/VKsT5ZDZM+Ho0FJwJ10JmkcDLS3XzZHtAAzTueYH/4tLSA+uRj1hvznCRb9YZcre7oMpQHI4ISaduwsLKBjtrqbNhMhw/ukfCbNH98Z+BKCqtLA61pxRaNzhgdZs9+3d4NE40NI/F7FZzttQadHa9YF2jyvrMleRjftBMhBTyo4xgF442CGoJueudr6MxcdHKn7Qi5Osxryzus3FT+tNkV5qsudkcXajV4ajzWkPkwn+RcAgXdfPEfjbMIMSf/rp70eTBLfI7fX9DINhzMs45UzRXZ2w2ZgrIuNd6Q8g7USdg9SU74NDy86"

    KAFKA_HOST="fantastic-gibbon-cp-kafka-headless"
    KAFKA_PORT="9092"