apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: product-redis
  labels:
    app: product-redis
spec:
  selector:
    matchLabels:
      app: product-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: product-redis
    spec:
      containers:
      - name: master
        image: redis
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: product-redis-service
  labels:
    app: product-redis-service
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: product-redis